/*
 * This file is generated by jOOQ.
 */
package no.nav.veilarblest.domain.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import jakarta.annotation.Generated;

import no.nav.veilarblest.domain.Indexes;
import no.nav.veilarblest.domain.Keys;
import no.nav.veilarblest.domain.Public;
import no.nav.veilarblest.domain.enums.Ressurs;
import no.nav.veilarblest.domain.tables.records.AndresRessurserRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AndresRessurser extends TableImpl<AndresRessurserRecord> {

    private static final long serialVersionUID = -234916864;

    /**
     * The reference instance of <code>public.andres_ressurser</code>
     */
    public static final AndresRessurser ANDRES_RESSURSER = new AndresRessurser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AndresRessurserRecord> getRecordType() {
        return AndresRessurserRecord.class;
    }

    /**
     * The column <code>public.andres_ressurser.id</code>.
     */
    public final TableField<AndresRessurserRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('lest_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.andres_ressurser.eier</code>.
     */
    public final TableField<AndresRessurserRecord, String> EIER = createField("eier", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.andres_ressurser.lest_av</code>.
     */
    public final TableField<AndresRessurserRecord, String> LEST_AV = createField("lest_av", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.andres_ressurser.ressurs</code>.
     */
    public final TableField<AndresRessurserRecord, Ressurs> RESSURS = createField("ressurs", org.jooq.impl.SQLDataType.VARCHAR.nullable(false).asEnumDataType(Ressurs.class), this, "");

    /**
     * The column <code>public.andres_ressurser.tidspunkt</code>.
     */
    public final TableField<AndresRessurserRecord, LocalDateTime> TIDSPUNKT = createField("tidspunkt", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * Create a <code>public.andres_ressurser</code> table reference
     */
    public AndresRessurser() {
        this(DSL.name("andres_ressurser"), null);
    }

    /**
     * Create an aliased <code>public.andres_ressurser</code> table reference
     */
    public AndresRessurser(String alias) {
        this(DSL.name(alias), ANDRES_RESSURSER);
    }

    /**
     * Create an aliased <code>public.andres_ressurser</code> table reference
     */
    public AndresRessurser(Name alias) {
        this(alias, ANDRES_RESSURSER);
    }

    private AndresRessurser(Name alias, Table<AndresRessurserRecord> aliased) {
        this(alias, aliased, null);
    }

    private AndresRessurser(Name alias, Table<AndresRessurserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AndresRessurser(Table<O> child, ForeignKey<O, AndresRessurserRecord> key) {
        super(child, key, ANDRES_RESSURSER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ANDRES_UNIKE_RESSURSER_LEST, Indexes.LEST_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AndresRessurserRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ANDRES_RESSURSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AndresRessurserRecord> getPrimaryKey() {
        return Keys.LEST_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AndresRessurserRecord>> getKeys() {
        return Arrays.<UniqueKey<AndresRessurserRecord>>asList(Keys.LEST_PKEY, Keys.ANDRES_UNIKE_RESSURSER_LEST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AndresRessurser as(String alias) {
        return new AndresRessurser(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AndresRessurser as(Name alias) {
        return new AndresRessurser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AndresRessurser rename(String name) {
        return new AndresRessurser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AndresRessurser rename(Name name) {
        return new AndresRessurser(name, null);
    }
}
