/*
 * This file is generated by jOOQ.
 */
package no.nav.veilarblest.domain.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import no.nav.veilarblest.domain.Indexes;
import no.nav.veilarblest.domain.Keys;
import no.nav.veilarblest.domain.Public;
import no.nav.veilarblest.domain.enums.Ressurs;
import no.nav.veilarblest.domain.tables.records.MineRessurserRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MineRessurser extends TableImpl<MineRessurserRecord> {

    private static final long serialVersionUID = 585124977;

    /**
     * The reference instance of <code>public.mine_ressurser</code>
     */
    public static final MineRessurser MINE_RESSURSER = new MineRessurser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MineRessurserRecord> getRecordType() {
        return MineRessurserRecord.class;
    }

    /**
     * The column <code>public.mine_ressurser.id</code>.
     */
    public final TableField<MineRessurserRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('mine_ressurser_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.mine_ressurser.eier</code>.
     */
    public final TableField<MineRessurserRecord, String> EIER = createField("eier", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.mine_ressurser.ressurs</code>.
     */
    public final TableField<MineRessurserRecord, Ressurs> RESSURS = createField("ressurs", org.jooq.impl.SQLDataType.VARCHAR.nullable(false).asEnumDataType(Ressurs.class), this, "");

    /**
     * The column <code>public.mine_ressurser.tidspunkt</code>.
     */
    public final TableField<MineRessurserRecord, LocalDateTime> TIDSPUNKT = createField("tidspunkt", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>public.mine_ressurser.verdi</code>.
     */
    public final TableField<MineRessurserRecord, String> VERDI = createField("verdi", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.mine_ressurser</code> table reference
     */
    public MineRessurser() {
        this(DSL.name("mine_ressurser"), null);
    }

    /**
     * Create an aliased <code>public.mine_ressurser</code> table reference
     */
    public MineRessurser(String alias) {
        this(DSL.name(alias), MINE_RESSURSER);
    }

    /**
     * Create an aliased <code>public.mine_ressurser</code> table reference
     */
    public MineRessurser(Name alias) {
        this(alias, MINE_RESSURSER);
    }

    private MineRessurser(Name alias, Table<MineRessurserRecord> aliased) {
        this(alias, aliased, null);
    }

    private MineRessurser(Name alias, Table<MineRessurserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> MineRessurser(Table<O> child, ForeignKey<O, MineRessurserRecord> key) {
        super(child, key, MINE_RESSURSER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MINE_RESSURSER_PKEY, Indexes.MINE_UNIKE_RESSURSER_LEST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MineRessurserRecord, Integer> getIdentity() {
        return Keys.IDENTITY_MINE_RESSURSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MineRessurserRecord> getPrimaryKey() {
        return Keys.MINE_RESSURSER_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MineRessurserRecord>> getKeys() {
        return Arrays.<UniqueKey<MineRessurserRecord>>asList(Keys.MINE_RESSURSER_PKEY, Keys.MINE_UNIKE_RESSURSER_LEST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MineRessurser as(String alias) {
        return new MineRessurser(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MineRessurser as(Name alias) {
        return new MineRessurser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MineRessurser rename(String name) {
        return new MineRessurser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MineRessurser rename(Name name) {
        return new MineRessurser(name, null);
    }
}
