# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veilarblest
team: oppfolging
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
webproxy: true
healthcheck:
  liveness:
    path: veilarblest/internal/isAliveForAWhile
    initialDelay: 20
  readiness:
    path: veilarblest/internal/isReadyForAWhile
    initialDelay: 20
prometheus:
  enabled: true
  path: veilarblest/internal/metrics
resources:
  limits:
    cpu: 2
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 768Mi
fasitResources:
  used:
  - alias: loadbalancer:veilarblest
    resourceType: loadbalancerconfig
  - alias: srvveilarblest
    resourceType: credential
  - alias: veilarblest.properties
    resourceType: applicationproperties
  - alias: appdynamics
    resourceType: applicationproperties
  - alias: securityTokenService
    resourceType: baseUrl
  - alias: Aktoer_v2
    resourceType: webserviceendpoint

    # ISSO
  - alias: isso-host
    resourceType: baseurl
  - alias: isso-jwks
    resourceType: baseurl
  - alias: isso-issuer
    resourceType: baseurl
  - alias: isso.isalive
    resourceType: baseurl
  - alias: isso-rp-user
    resourceType: credential
  - alias: veilarblogin.redirect-url
    resourceType: restservice
  - alias: aad_b2c_clientid
    resourceType: credential
  - alias: veilarbazureadproxy_discovery
    resourceType: restservice

  exposed:
  - alias: veilarblestAPI
    resourceType: restservice
    path: /veilarblest/api
alertProfiles:
  - common-java-modules
secrets: true
