# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veilarblest
team: oppfolging
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
webproxy: true
healthcheck:
  liveness:
    path: veilarblest/internal/isAlive
    initialDelay: 20
  readiness:
    path: veilarblest/internal/isReady
    initialDelay: 20
prometheus:
  enabled: true
  path: veilarblest/internal/metrics
resources:
  limits:
    cpu: 2
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 768Mi
fasitResources:
  used:
  - alias: loadbalancer:veilarblest
    resourceType: loadbalancerconfig
  - alias: srvveilarblest
    resourceType: credential
  - alias: appdynamics
    resourceType: applicationproperties
  exposed:
  - alias: veilarblestAPI
    resourceType: restservice
    path: /veilarblest/api
alertProfiles:
  - common-java-modules
secrets: true
