kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarblest
  namespace: pto
  cluster: dev-fss
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/veilarblest/veilarblest:{{version}}
  ingresses:
    - https://veilarblest-q1.nais.preprod.local
    - https://app-q1.adeo.no/veilarblest
    - https://app-q1.dev.adeo.no/veilarblest
    - https://app.dev.adeo.no/veilarblest
    - https://veilarblest.dev-fss-pub.nais.io
  webproxy: true
  port: 8080
  prometheus:
    enabled: true
    path: veilarblest/internal/prometheus
  liveness:
    path: veilarblest/internal/isAlive
    initialDelay: 20
  readiness:
    path: veilarblest/internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  kafka:
    pool: nav-dev
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvveilarblest
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/preprod/fss/veilarblest/q1
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: VEILARBLEST_DB_URL
      value: jdbc:postgresql://B27DBVL003.preprod.local:5432/veilarblest-q1
    - name: APP_ENVIRONMENT_NAME
      value: q1
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbpersonflate
          namespace: poao
          cluster: dev-gcp
        - application: aktivitetsplan
          namespace: pto
          cluster: dev-gcp
