kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarblest
  namespace: pto
  labels:
    team: pto
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: veilarblest/internal/prometheus
  liveness:
    path: veilarblest/internal/isAlive
    initialDelay: 20
  readiness:
    path: veilarblest/internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  envFrom:
    - configmap: pto-config
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
            - name: veilarblest
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbpersonflate
        - application: aktivitetsplan
