kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarblest
  namespace: default
  cluster: prod-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarblest/veilarblest:{{version}}
  ingresses:
    - https://veilarblest.nais.adeo.no
    - https://app.adeo.no/veilarblest
    - https://veilarblest.prod-fss-pub.nais.io
  webproxy: true
  port: 8080
  prometheus:
    enabled: true
    path: veilarblest/internal/prometheus
  liveness:
    path: veilarblest/internal/isAlive
    port: 8080
    initialDelay: 20
  readiness:
    path: veilarblest/internal/isReady
    port: 8080
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: "1"
      memory: 1024Mi
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvveilarblest
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/prod/fss/veilarblest/default
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: VEILARBLEST_DB_URL
      value: jdbc:postgresql://fsspgdb.adeo.no:5432/veilarblest
    - name: APP_ENVIRONMENT_NAME
      value: p
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbpersonflate
          namespace: poao
          cluster: prod-gcp
