kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarblest
  namespace: dab
  labels:
    team: dab
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: veilarblest/internal/prometheus
  liveness:
    path: veilarblest/internal/isAlive
    port: 8080
    initialDelay: 20
  readiness:
    path: veilarblest/internal/isReady
    port: 8080
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: "1"
      memory: 1024Mi
  envFrom:
    - configmap: pto-config
  kafka:
    pool: nav-prod
  env:
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
  tokenx:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name: veilarblest
  azure:
    application:
      enabled: true
      allowAllUsers: true #todo burde vi legge inn noen roller her?
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbpersonflate
          namespace: poao
        - application: aktivitetsplan
          namespace: pto
    outbound:
      external:
        - host: https://pdl-api.prod-fss-pub.nais.io
