/*
 * This file is generated by jOOQ.
 */
package no.nav.veilarblest.domain;


import jakarta.annotation.Generated;

import no.nav.veilarblest.domain.tables.AndresRessurser;
import no.nav.veilarblest.domain.tables.MineRessurser;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ANDRES_UNIKE_RESSURSER_LEST = Indexes0.ANDRES_UNIKE_RESSURSER_LEST;
    public static final Index LEST_PKEY = Indexes0.LEST_PKEY;
    public static final Index MINE_RESSURSER_PKEY = Indexes0.MINE_RESSURSER_PKEY;
    public static final Index MINE_UNIKE_RESSURSER_LEST = Indexes0.MINE_UNIKE_RESSURSER_LEST;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ANDRES_UNIKE_RESSURSER_LEST = Internal.createIndex("andres_unike_ressurser_lest", AndresRessurser.ANDRES_RESSURSER, new OrderField[] { AndresRessurser.ANDRES_RESSURSER.LEST_AV, AndresRessurser.ANDRES_RESSURSER.EIER, AndresRessurser.ANDRES_RESSURSER.RESSURS }, true);
        public static Index LEST_PKEY = Internal.createIndex("lest_pkey", AndresRessurser.ANDRES_RESSURSER, new OrderField[] { AndresRessurser.ANDRES_RESSURSER.ID }, true);
        public static Index MINE_RESSURSER_PKEY = Internal.createIndex("mine_ressurser_pkey", MineRessurser.MINE_RESSURSER, new OrderField[] { MineRessurser.MINE_RESSURSER.ID }, true);
        public static Index MINE_UNIKE_RESSURSER_LEST = Internal.createIndex("mine_unike_ressurser_lest", MineRessurser.MINE_RESSURSER, new OrderField[] { MineRessurser.MINE_RESSURSER.EIER, MineRessurser.MINE_RESSURSER.RESSURS }, true);
    }
}
