/*
 * This file is generated by jOOQ.
 */
package no.nav.veilarblest.domain;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import jakarta.annotation.Generated;

import no.nav.veilarblest.domain.tables.AndresRessurser;
import no.nav.veilarblest.domain.tables.MineRessurser;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -450115805;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.andres_ressurser</code>.
     */
    public final AndresRessurser ANDRES_RESSURSER = AndresRessurser.ANDRES_RESSURSER;

    /**
     * The table <code>public.mine_ressurser</code>.
     */
    public final MineRessurser MINE_RESSURSER = MineRessurser.MINE_RESSURSER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.LEST_ID_SEQ,
            Sequences.MINE_RESSURSER_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AndresRessurser.ANDRES_RESSURSER,
            MineRessurser.MINE_RESSURSER);
    }
}
