/*
 * This file is generated by jOOQ.
 */
package no.nav.veilarblest.domain.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import no.nav.veilarblest.domain.enums.Ressurs;
import no.nav.veilarblest.domain.tables.MineRessurser;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MineRessurserRecord extends UpdatableRecordImpl<MineRessurserRecord> implements Record5<Integer, String, Ressurs, LocalDateTime, String> {

    private static final long serialVersionUID = 1874751558;

    /**
     * Setter for <code>public.mine_ressurser.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mine_ressurser.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.mine_ressurser.eier</code>.
     */
    public void setEier(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mine_ressurser.eier</code>.
     */
    public String getEier() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.mine_ressurser.ressurs</code>.
     */
    public void setRessurs(Ressurs value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mine_ressurser.ressurs</code>.
     */
    public Ressurs getRessurs() {
        return (Ressurs) get(2);
    }

    /**
     * Setter for <code>public.mine_ressurser.tidspunkt</code>.
     */
    public void setTidspunkt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mine_ressurser.tidspunkt</code>.
     */
    public LocalDateTime getTidspunkt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.mine_ressurser.verdi</code>.
     */
    public void setVerdi(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mine_ressurser.verdi</code>.
     */
    public String getVerdi() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Ressurs, LocalDateTime, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Ressurs, LocalDateTime, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MineRessurser.MINE_RESSURSER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MineRessurser.MINE_RESSURSER.EIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Ressurs> field3() {
        return MineRessurser.MINE_RESSURSER.RESSURS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return MineRessurser.MINE_RESSURSER.TIDSPUNKT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MineRessurser.MINE_RESSURSER.VERDI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getEier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Ressurs component3() {
        return getRessurs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component4() {
        return getTidspunkt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getVerdi();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Ressurs value3() {
        return getRessurs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getTidspunkt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getVerdi();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MineRessurserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MineRessurserRecord value2(String value) {
        setEier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MineRessurserRecord value3(Ressurs value) {
        setRessurs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MineRessurserRecord value4(LocalDateTime value) {
        setTidspunkt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MineRessurserRecord value5(String value) {
        setVerdi(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MineRessurserRecord values(Integer value1, String value2, Ressurs value3, LocalDateTime value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MineRessurserRecord
     */
    public MineRessurserRecord() {
        super(MineRessurser.MINE_RESSURSER);
    }

    /**
     * Create a detached, initialised MineRessurserRecord
     */
    public MineRessurserRecord(Integer id, String eier, Ressurs ressurs, LocalDateTime tidspunkt, String verdi) {
        super(MineRessurser.MINE_RESSURSER);

        set(0, id);
        set(1, eier);
        set(2, ressurs);
        set(3, tidspunkt);
        set(4, verdi);
    }
}
