/*
 * This file is generated by jOOQ.
 */
package no.nav.fo.veilarblest.domain;


import javax.annotation.Generated;

import no.nav.fo.veilarblest.domain.tables.Lest;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index LEST_PKEY = Indexes0.LEST_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index LEST_PKEY = Internal.createIndex("lest_pkey", Lest.LEST, new OrderField[] { Lest.LEST.ID }, true);
    }
}
