/*
 * This file is generated by jOOQ.
 */
package no.nav.fo.veilarblest.domain;


import javax.annotation.Generated;

import no.nav.fo.veilarblest.domain.tables.Lest;
import no.nav.fo.veilarblest.domain.tables.records.LestRecord;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<LestRecord, Integer> IDENTITY_LEST = Identities0.IDENTITY_LEST;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LestRecord> LEST_PKEY = UniqueKeys0.LEST_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<LestRecord, Integer> IDENTITY_LEST = Internal.createIdentity(Lest.LEST, Lest.LEST.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<LestRecord> LEST_PKEY = Internal.createUniqueKey(Lest.LEST, "lest_pkey", Lest.LEST.ID);
    }
}
