/*
 * This file is generated by jOOQ.
 */
package no.nav.fo.veilarblest.domain;


import javax.annotation.Generated;

import no.nav.fo.veilarblest.domain.tables.AndresRessurser;
import no.nav.fo.veilarblest.domain.tables.MineRessurser;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.andres_ressurser</code>.
     */
    public static final AndresRessurser ANDRES_RESSURSER = no.nav.fo.veilarblest.domain.tables.AndresRessurser.ANDRES_RESSURSER;

    /**
     * The table <code>public.mine_ressurser</code>.
     */
    public static final MineRessurser MINE_RESSURSER = no.nav.fo.veilarblest.domain.tables.MineRessurser.MINE_RESSURSER;
}
