/*
 * This file is generated by jOOQ.
 */
package no.nav.fo.veilarblest.domain;


import javax.annotation.Generated;

import no.nav.fo.veilarblest.domain.tables.Lest;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.lest</code>.
     */
    public static final Lest LEST = no.nav.fo.veilarblest.domain.tables.Lest.LEST;
}
